"""

Given a string, we have to find out all subsequences 
of it. A String is a subsequence of a given String, that 
is generated by deleting some character of a 
given string without changing its order.


"""

# Recursive Approch (Pick and Don’t Pick Concept)


def SubSeq(st, ot=""):
    if len(st) == 0:
        print(ot, end=" ")
        return

    SubSeq(st[1:], ot+st[0])
    SubSeq(st[1:], ot)


SubSeq('abcd')
